using System.Collections.Generic;
using System.Globalization;
using System.IO;

namespace NavMeshBaker;

public static class ObjWriter
{
    // Writes a triangle soup as OBJ, welding coincident vertices first. The weld is essential:
    // Recast's detail mesh duplicates vertices across sub-mesh seams, and without welding those
    // seams would load as boundary (wall) edges instead of walkable connections.
    public static void Write(TextWriter w, TriangleSoup soup, float weldEps = 1e-3f)
    {
        var canonical = new List<float>();
        var grid = new Dictionary<(long, long, long), int>();
        var remap = new int[soup.VertexCount];
        float inv = 1f / weldEps;

        for (int i = 0; i < soup.VertexCount; i++)
        {
            float x = soup.Verts[i * 3 + 0], y = soup.Verts[i * 3 + 1], z = soup.Verts[i * 3 + 2];
            var key = ((long)System.MathF.Round(x * inv), (long)System.MathF.Round(y * inv), (long)System.MathF.Round(z * inv));
            if (!grid.TryGetValue(key, out int idx))
            {
                idx = canonical.Count / 3;
                canonical.Add(x); canonical.Add(y); canonical.Add(z);
                grid[key] = idx;
            }
            remap[i] = idx;
        }

        w.WriteLine("# navmesh generated by NavMeshBaker (Recast/DotRecast)");
        for (int i = 0; i < canonical.Count; i += 3)
            w.WriteLine(string.Format(CultureInfo.InvariantCulture, "v {0} {1} {2}",
                canonical[i], canonical[i + 1], canonical[i + 2]));

        for (int t = 0; t < soup.TriangleCount; t++)
        {
            int a = remap[soup.Tris[t * 3 + 0]];
            int b = remap[soup.Tris[t * 3 + 1]];
            int c = remap[soup.Tris[t * 3 + 2]];
            if (a == b || b == c || c == a) continue; // drop degenerates created by welding
            w.WriteLine($"f {a + 1} {b + 1} {c + 1}");
        }
    }
}
